# Used to config the <pointfusion.datasets.SereactDataset.SereactDataset> class
dataset: 
  processed_data_path:  # must be specified
  batch_size: 1
  num_workers: 11
  val_split_ratio: 0.1
  test_split_ratio: 0.1
  seed: 42


# Used to config the <pointfusion.models.pointfusion.PointFusionLit> class
model:
  num_points: 50176 # 224 * 224 if window size was 224
  fusion_type: global
  learning_rate: 0.001
  draw_bbox: True

# Used to config the <pytorch_lightning.trainer.Trainer> class
trainer:
  accelerator: gpu
  devices: auto
  logger: True
  min_epochs: 1
  max_epochs: 1
  onxx_dir_path: onxx_models
  onxx_file_name: pointfusion.onnx